baseURL: "https://harderth.github.io" 
title: Thorleif Harder
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1
        - name: Blog
          url: blog/
          weight: 2
        - name: About me
          url: about-me/
          weight: 3

params:
    description: "I am a **Research Associate** at the Institut of Interactive Systems at the **Technical University of Applied Sciences Lübeck**. My research focuses on human-computer interaction and human-centered design."
    author: Thorleif Harder
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Thorleif Harder
          subtitle: "I am a **Research Associate** at the Institut of Interactive Systems at the **Technical University of Applied Sciences Lübeck**. My research focuses on human-computer interaction and human-centered design. I am involved in various projects, including analyzing success and dropout factors in digital study programs and developing AI-based solutions to foster innovation in the economy."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Thorleif Harder
          buttons:
            - name: Publications
              url: publications/
            - name: Blog
              url: blog/
            - name: About me
              url: about-me/
          # - name: Tags
          #    url: tags/
          #  - name: Archive
          #    url: archive/
    socialIcons:
      #  - name: CV
      #    url: cv.pdf
        - name: Email
          url: mailto:thorleif.harder@th-luebeck.de
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=7dkt0CcAAAAJ&hl=en
        - name: orcid
          url: https://orcid.org/0000-0002-9099-2351
        - name: Twitter
          url: https://twitter.com/thorleifharder
        - name: Linkedin
          url: https://www.linkedin.com/in/thorleif-harder-8981a2193/
        
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Thorleif Harder"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
